project:
  type: website
  output-dir: docs

website:
  title: "testwebsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - publications.qmd
      - cv.qmd

format:
  html:
    theme: vapor
    fontcolor: lightgrey
    css: styles.css
    toc: true

editor: visual

